trigger:
  - master

jobs:
  - job: npm
    pool:
      name: Azure Pipelines
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false

      - task: Npm@1
        displayName: 'Run unit and integration tests: testing api and bd connection'
        inputs:
          command: custom
          verbose: false
          customCommand: ' run integration-test'

      - task: PublishTestResults@2
        displayName: 'Publish tests results'
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: '**/test-results.xml'

      - task: PublishCodeCoverageResults@1
        displayName: 'Code coverage'
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/.test_output/coverage/cobertura-coverage.xml'
          pathToSources: '$(System.DefaultWorkingDirectory)/.test_output/coverage'
          reportDirectory: '$(System.DefaultWorkingDirectory)/.test_output'

  - job: docker
    dependsOn: npm
    pool:
      name: Azure Pipelines
    steps:
      - task: Docker@2
        displayName: login
        inputs:
          containerRegistry: 'malabareand dockerHub'
          command: login

      - task: Docker@2
        displayName: buildAndPush
        inputs:
          containerRegistry: 'malabareand dockerHub'
          repository: 'malabareand/drtd-api'
          Dockerfile: Dockerfile

      - task: CopyFiles@2
        displayName: 'Copy deployment & service files'
        inputs:
          SourceFolder: k8
          Contents: '*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact in drop folder'
