apiVersion: apps/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: drtd-api
  labels:
    app: drtd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drtd-api
  template:
    metadata:
      labels:
        app: drtd-api
    spec:
      containers:
        - name: drtd-api
          image: drtd.azurecr.io/drtd-api:#{Build.BuildId}#
          env:
            - name: VERSION_API
              value: "0.0.1"
            - name: NODE_ENV
              value: "#{NODE_ENV_VG}#"
            - name: IS_LOCAL
              value: ""
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: azureregistryisapre
